### ISSUE TITLE
Loading sequence: minimum photo display time

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/MillValley1920#21]
On some machines, the photos that appear during project loading will flash on for only a second or two.  Please ensure that each photo is shown for a minimum of X seconds (3 by default) before being replaced.

Note: I added several more photo/sprites to the project and added them into the display queue.

**Comment by ericboise** [comment]
Set images to 3f realtime seconds wait, added MainScene to preloaded assets in playersettings to try to smooth loading
