### ISSUE TITLE
Enable scrollable text for ReadMe

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/MillValley1920#26]
The historical and design notes contained in the README.md for each building should be readable while in-world (both in VR and Walkthrough mode) when in the "Commentary" mode (i.e. pressed "C").  For example, if the user is standing next to the Dowd's Moving building and in "Commentary" mode, then this page should be visible: https://github.com/TimeWalkOrg/building-mill-valley-ca-dowds-moving/blob/master/README.md

Ideally...

- we can somehow display the actual HTML or Rich Text version of this page, straight from a URL, including images
- the page would be scrollable (since the length will vary and some are quite long)
- the page would be readable even when in VR (maybe it takes over the left half of the screen somehow?)

**Comment by ericboise** [comment]
Move to ! mesh and the web view is in overlay canvas mode in FPS and in world mesh/canvas in VR.
Use the mouse to navigate in FPS and the VR controller to point and trigger to navigate in VR mode.
In VR mode to exit use the left touch pad to point and press trigger to select X or BACK
