### ISSUE TITLE
Display controller instructions when in VR

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/MillValley1920#27]
To orient VR users to TimeWalk, we need to display simple callouts describing each of the buttons on the Oculus Touch controller.  These should appear "A" seconds after the scene loads, and disappear when the Select button (Button.Start) is pressed.  The callouts would read as follows:

B (Button.Two) = Toggle Night/Day
A (Button.One) = See Commentary
Y (Button.Four) = Time Travel Forward
X (Button.Three) = Time Travel Back
Select (Button.Start) = Toggle Help

Example of a button callout, from TiltBrush:
![vlcsnap-2017-02-12-23h51m25s468](https://user-images.githubusercontent.com/694013/37938203-ee11a5e2-3111-11e8-930a-2f86375c02ed.jpg)

**Comment by ericboise** [comment]
Buttons for Oculus are set A - Commentary B - Night/Day X - Timewalk back Y - Timewalk forward and glance at controllers activates help
